server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    error_log  /var/log/nginx/backend_error.log;
    access_log /var/log/nginx/backend_access.log;

    resolver 127.0.0.11 valid=10s;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        set $upstream time-reserve-backend:9000;
        fastcgi_pass $upstream;

        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
