# fly.toml app configuration file generated for back-end-wild-shape-9497 on 2026-02-20T23:34:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'back-end-wild-shape-9497'
primary_region = 'fra'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\\Formatter\\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true

  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  processes = ['app']

[processes]
  app = "php artisan serve --host 0.0.0.0 --port 8080"
  worker = "php artisan queue:work --tries=3"
  cron = "php artisan schedule:work"

[[vm]]
processes = ["app"]
memory_mb = 512
cpus = 1
cpu_kind = "shared"

[[vm]]
processes = ["worker"]
memory_mb = 128
cpus = 1
cpu_kind = "shared"

[[vm]]
processes = ["cron"]
memory_mb = 128
cpus = 1
cpu_kind = "shared"
